# 1. 파일 불러오기

In [6]:
import pandas as pd
import numpy as np

In [7]:
from matplotlib import font_manager, rc
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['axes.unicode_minus'] = False  # minus 표시
plt.rc('font', family='Malgun Gothic')

In [9]:
file_path = './resources/완_기간별_일별_170101_to_230509_ver1.csv'
mv_2017 = pd.read_csv(file_path)
mv_2017

,순위,영화명,개봉일,대표국적,국적,제작사,배급사,등급,장르,감독,배우,기준일,매출액,누적매출액,관객수,누적관객수,스크린수,상영횟수
0,1,너의 이름은.,2017-01-04 00:00:00,일본,일본,NaN,플러스엠 엔터테인먼트,12세이상관람가,"애니메이션,드라마,멜로/로맨스",신카이 마코토,"카미키 류노스케,카미시라이시 모네,나가사와 마사미,이치하라 에수코,유키 아오이,시마...",2017-01-08,2809088900,9745292442,333008,1182465,947,4101
1,3,모아나,2017-01-12 00:00:00,미국,미국,NaN,월트디즈니컴퍼니코리아 유한책임회사,전체관람가,애니메이션,"론 클레멘츠,존 머스커","드웨인 존슨,아우이 크라발호,알란 터딕,제메인 클레멘트,테무에라 모리슨",2017-01-08,7738000,9712000,910,1192,6,6
2,4,패신저스,2017-01-04 00:00:00,미국,미국,NaN,유니버설픽쳐스인터내셔널 코리아(유),12세이상관람가,"어드벤처,SF",모튼 틸덤,"크리스 프랫,제니퍼 로렌스,마이클 쉰,앤디 가르시아,로렌스 피쉬번",2017-01-08,1107502600,4176443418,129810,504393,608,2272
3,5,얼라이드,2017-01-11 00:00:00,미국,미국,NaN,롯데쇼핑㈜롯데엔터테인먼트,15세이상관람가,"스릴러,드라마,멜로/로맨스",로버트 저메키스,"브래드 피트,마리옹 꼬띠아르,리지 캐플란,매튜 구드,자레드 해리스",2017-01-08,0,32151000,0,3730,0,0
4,6,어쌔신 크리드,2017-01-11 00:00:00,미국,"미국,영국,프랑스",NaN,이십세기폭스코리아(주),15세이상관람가,"액션,어드벤처,판타지,SF",저스틴 커젤,"마이클 패스벤더,마리옹 꼬띠아르,아리안 라베드,제레미 아이언스,브렌단 글리슨,마이클...",2017-01-08,0,8289000,0,790,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363267,187,일본 온천 여행기,2017-01-05 00:00:00,일본,일본,NaN,(주)도키엔터테인먼트,청소년관람불가,성인물(에로),칸바라 이쿠토,카미노 이즈미,2017-01-07,0,8000,0,1,0,0
363268,187,중년남과 고양이 여인의 동거,2017-01-02 00:00:00,일본,일본,NaN,(주)도키엔터테인먼트,청소년관람불가,성인물(에로),카네다 사토시,"쿠라모치 유카,하츠미 사키",2017-01-07,0,8000,0,1,0,0
363269,187,추천 극상 오일마사지,2017-01-05 00:00:00,일본,일본,NaN,(주)도키엔터테인먼트,청소년관람불가,성인물(에로),칸바라 나오토,나가사와 아즈사,2017-01-07,0,8000,0,1,0,0
363270,187,하드코어 미망인,2017-01-02 00:00:00,일본,일본,NaN,(주)도키엔터테인먼트,청소년관람불가,성인물(에로),세키네 카즈미,미야노 유카나,2017-01-07,0,8000,0,1,0,0
363271,212,문영,2017-01-12 00:00:00,한국,한국,NaN,KT&G 상상마당 영화사업팀 컴퍼니에스에스(주),15세이상관람가,드라마,김소연,"김태리,정현,박완규,박정식",2017-01-07,0,2819699,0,350,0,0

In [ ]:
# 개봉일
mv_2017['기준일'] = pd.to_datetime(mv_2017['기준일'],format='%Y-%m-%d')

In [8]:
file_path_ver2 = './resources/완_기간별_일별_170101_to_230509_ver2.xlsx'
mv_2017_ver2 = pd.read_excel(file_path_ver2)
mv_2017_ver2.head()

,순위,영화명,개봉일,대표국적,국적,제작사,배급사,등급,장르,감독,...,매출액,누적매출액,관객수,누적관객수,스크린수,상영횟수,기준연도,기준월,개봉연도,개봉월
0,1,너의 이름은.,2017-01-04,일본,일본,NaN,플러스엠 엔터테인먼트,12세이상관람가,"애니메이션,드라마,멜로/로맨스",신카이 마코토,...,2809088900,9745292442,333008,1182465,947,4101,2017,1,2017,1
1,3,모아나,2017-01-12,미국,미국,NaN,월트디즈니컴퍼니코리아 유한책임회사,전체관람가,애니메이션,"론 클레멘츠,존 머스커",...,7738000,9712000,910,1192,6,6,2017,1,2017,1
2,4,패신저스,2017-01-04,미국,미국,NaN,유니버설픽쳐스인터내셔널 코리아(유),12세이상관람가,"어드벤처,SF",모튼 틸덤,...,1107502600,4176443418,129810,504393,608,2272,2017,1,2017,1
3,9,눈의 여왕 3: 눈과 불의 마법대결,2017-01-04,러시아,러시아,NaN,(주)이수C&E,전체관람가,"애니메이션,어드벤처,가족,판타지",알렉세이 트시칠린,...,535436000,1828596400,67605,242171,524,1163,2017,1,2017,1
4,10,사랑하기 때문에,2017-01-04,한국,한국,(주)에이디사공육,(주)넥스트엔터테인먼트월드(NEW),12세이상관람가,"코미디,멜로/로맨스",주지홍,...,450612400,1968850940,53856,246167,542,1533,2017,1,2017,1

In [24]:
mv_2017_ver2.head()

,순위,영화명,개봉일,대표국적,국적,제작사,배급사,등급,장르,감독,...,매출액,누적매출액,관객수,누적관객수,스크린수,상영횟수,기준연도,기준월,개봉연도,개봉월
0,1,너의 이름은.,2017-01-04,일본,일본,NaN,플러스엠 엔터테인먼트,12세이상관람가,"애니메이션,드라마,멜로/로맨스",신카이 마코토,...,2809088900,9745292442,333008,1182465,947,4101,2017,1,2017,1
1,3,모아나,2017-01-12,미국,미국,NaN,월트디즈니컴퍼니코리아 유한책임회사,전체관람가,애니메이션,"론 클레멘츠,존 머스커",...,7738000,9712000,910,1192,6,6,2017,1,2017,1
2,4,패신저스,2017-01-04,미국,미국,NaN,유니버설픽쳐스인터내셔널 코리아(유),12세이상관람가,"어드벤처,SF",모튼 틸덤,...,1107502600,4176443418,129810,504393,608,2272,2017,1,2017,1
3,9,눈의 여왕 3: 눈과 불의 마법대결,2017-01-04,러시아,러시아,NaN,(주)이수C&E,전체관람가,"애니메이션,어드벤처,가족,판타지",알렉세이 트시칠린,...,535436000,1828596400,67605,242171,524,1163,2017,1,2017,1
4,10,사랑하기 때문에,2017-01-04,한국,한국,(주)에이디사공육,(주)넥스트엔터테인먼트월드(NEW),12세이상관람가,"코미디,멜로/로맨스",주지홍,...,450612400,1968850940,53856,246167,542,1533,2017,1,2017,1

In [25]:
mv_2017_ver2.loc[0,'개봉일']

Timestamp('2017-01-04 00:00:00')

In [10]:
# ver2 csv 파일
file_path_csv_2 = './resources/완_기간별_일별_170101_to_230509_ver2.csv'
mv_2017_csv_2 = pd.read_csv(file_path_csv_2)
mv_2017_csv_2

,순위,영화명,개봉일,대표국적,국적,제작사,배급사,등급,장르,감독,...,매출액,누적매출액,관객수,누적관객수,스크린수,상영횟수,기준연도,기준월,개봉연도,개봉월
0,1,너의 이름은.,2017-01-04,일본,일본,NaN,플러스엠 엔터테인먼트,12세이상관람가,"애니메이션,드라마,멜로/로맨스",신카이 마코토,...,2809088900,9745292442,333008,1182465,947,4101,2017,1,2017,1
1,3,모아나,2017-01-12,미국,미국,NaN,월트디즈니컴퍼니코리아 유한책임회사,전체관람가,애니메이션,"론 클레멘츠,존 머스커",...,7738000,9712000,910,1192,6,6,2017,1,2017,1
2,4,패신저스,2017-01-04,미국,미국,NaN,유니버설픽쳐스인터내셔널 코리아(유),12세이상관람가,"어드벤처,SF",모튼 틸덤,...,1107502600,4176443418,129810,504393,608,2272,2017,1,2017,1
3,9,눈의 여왕 3: 눈과 불의 마법대결,2017-01-04,러시아,러시아,NaN,(주)이수C&E,전체관람가,"애니메이션,어드벤처,가족,판타지",알렉세이 트시칠린,...,535436000,1828596400,67605,242171,524,1163,2017,1,2017,1
4,10,사랑하기 때문에,2017-01-04,한국,한국,(주)에이디사공육,(주)넥스트엔터테인먼트월드(NEW),12세이상관람가,"코미디,멜로/로맨스",주지홍,...,450612400,1968850940,53856,246167,542,1533,2017,1,2017,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183001,73,돈 지오반니,2017-01-07,미국,미국,NaN,(주) 인스터 글로벌,전체관람가,공연,NaN,...,4881000,4881000,209,209,6,6,2017,1,2017,1
183002,75,걱정말아요,2017-01-05,한국,한국,(주)레인보우팩토리,(주)레인보우팩토리,청소년관람불가,드라마,"소준문,김대견,신종훈",...,502000,2811100,71,373,11,15,2017,1,2017,1
183003,149,비밀객잔의 결투,2017-01-04,중국,중국,NaN,(주)케이알씨지,12세이상관람가,"액션,어드벤처,드라마",유신의,...,7000,61000,2,17,2,2,2017,1,2017,1
183004,156,소림사 무림 탐정-취의전장,2017-01-05,중국,중국,NaN,(주)케이알씨지,12세이상관람가,액션,해도,...,7000,43000,2,12,2,2,2017,1,2017,1
183005,160,더티 로맨스,2017-01-07,한국,한국,이상우필름,이상우필름,청소년관람불가,드라마,이상우,...,62000,62000,9,9,1,1,2017,1,2017,1

# 데이터 CSV, EXCEL 저장

In [20]:
mv_2017_csv_2 = mv_2017_csv_2[mv_2017_csv_2['기준연도'] > 2017]
df_order = mv_2017_csv_2.sort_values(by=['기준일', '순위'])
df_order = df_order.reset_index(drop=True)
df_order.to_csv('./resources/완_기간별_ordered_180101_to_230509_ver3.csv', index=False, encoding='UTF-8')
df_order.to_excel('./resources/완_기간별_ordered_180101_to_230509_ver3.xlsx', index=False)

In [22]:
df_order.iloc[:,5:].head(15)

,제작사,배급사,등급,장르,감독,배우,기준일,매출액,누적매출액,관객수,누적관객수,스크린수,상영횟수,기준연도,기준월,개봉연도,개봉월
0,"리얼라이즈픽쳐스(주),(주)덱스터스튜디오",롯데쇼핑㈜롯데엔터테인먼트,12세이상관람가,"판타지,드라마",김용화,"하정우,차태현,주지훈,김향기,마동석,김동욱,도경수,오달수,임원희,장광,정해균,김수안...",2018-01-01,7715149100,76065645532,916652,9456147,1644,7957,2018,1,2017,12
1,(주)우정필름,(주)씨제이이엔엠,15세이상관람가,드라마,장준환,"안대겸,김윤석,하정우,유해진,김태리,박희순,이희준,설경구,여진구,윤재국,지웅배,정재...",2018-01-01,4460462100,19714466137,531469,2473546,1097,4982,2018,1,2017,12
2,"(주)와이웍스엔터테인먼트,(주)브이에이스튜디오",(주)넥스트엔터테인먼트월드(NEW),15세이상관람가,"액션,드라마",양우석,"정우성,곽도원,김갑수,김의성,이경영,조우진,정원중,김명곤,박은혜,김지호,안미나,원진...",2018-01-01,944228600,32939126166,114298,4128591,602,1451,2018,1,2017,12
3,NaN,"월트디즈니컴퍼니코리아 유한책임회사,이십세기폭스코리아(주)",12세이상관람가,"드라마,뮤지컬",마이클 그레이시,"휴 잭맨,잭 에프런,미쉘 윌리엄스,레베카 퍼거슨,젠데이아 콜먼",2018-01-01,509947700,7166974900,60070,874655,432,843,2018,1,2017,12
4,NaN,(주)이수C&E,전체관람가,"애니메이션,어드벤처,가족",유야마 쿠니히코,NaN,2018-01-01,262886500,3380416200,34103,449358,417,605,2018,1,2017,12
5,NaN,"CGV아트하우스,그린나래미디어(주)",전체관람가,드라마,스티븐 크보스키,"줄리아 로버츠,오웬 윌슨,제이콥 트렘블레이",2018-01-01,158549600,790939300,19322,101002,183,378,2018,1,2017,12
6,NaN,(주)키다리이엔티,전체관람가,애니메이션,호거 태프,"에밀리 왓슨,닉 프로스트",2018-01-01,205793300,2736976000,26521,368135,342,463,2018,1,2017,12
7,(주)오콘,(주)넥스트엔터테인먼트월드(NEW),전체관람가,애니메이션,"김현호,윤제완","이선,이미자,함수정,홍소영,정미숙,김서영,김환진,엄상현",2018-01-01,109207600,5958096200,13750,787493,195,270,2018,1,2017,12
8,NaN,(주)박수엔터테인먼트,전체관람가,애니메이션,모리와키 마코토,NaN,2018-01-01,47882900,327731800,5940,42390,166,246,2018,1,2017,12
9,NaN,월트디즈니컴퍼니코리아 유한책임회사,12세이상관람가,"액션,어드벤처,판타지,SF",라이언 존슨,"마크 해밀,캐리 피셔,아담 드라이버,데이지 리들리,존 보예가,오스카 아이삭,루피타 ...",2018-01-01,35090500,8570976561,3298,949845,35,42,2018,1,2017,12
10,NaN,그린나래미디어(주),12세이상관람가,드라마,짐 자무쉬,"아담 드라이버,골시프테 파라하니",2018-01-01,23044100,260880400,2644,31921,36,74,2018,1,2017,12
11,NaN,"(주)스튜디오디에이치엘,판씨네마(주)",15세이상관람가,"애니메이션,미스터리","도로타 코비엘라,휴 웰치맨","시얼샤 로넌,제롬 플린,크리스 오다우드,더글라스 부스,에이단 터너,헬렌 맥크로리",2018-01-01,21478000,3082934861,2432,386972,42,57,2018,1,2017,11
12,NaN,(주)팝엔터테인먼트,청소년관람불가,스릴러,프랑수아 오종,"마린 백트,제레미 레니에",2018-01-01,6215600,53506900,759,6541,38,52,2018,1,2017,12
13,NaN,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,전체관람가,"애니메이션,어드벤처",티모시 렉카트,"스티븐 연,지나 로드리게즈,제커리 리바이,오프라 윈프리",2018-01-01,12804700,474590200,1570,63652,56,59,2018,1,2017,12
14,NaN,"(주)이수C&E,(주)에이원엔터테인먼트",전체관람가,애니메이션,고로 사쿠라,NaN,2018-01-01,8096500,432762200,1039,56027,19,21,2018,1,2017,12