In [1]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import matplotlib.cm as cm
mpl.rcParams['font.family'] ='Malgun Gothic'
mpl.rcParams['axes.unicode_minus'] =False

plt.rcParams['font.family'] ='Malgun Gothic'
plt.rcParams['axes.unicode_minus'] =False

In [57]:
filmo_data = pd.read_excel('./use_data/필모그래피_통합.xlsx', engine='openpyxl')
filmo_data

,배급사,영화명,영화명(영문),제작연도,제작국가,장르,분야,공식통계 매출액,공식통계 관객수,KOBIS통계 매출액,KOBIS통계 관객수
0,(주)넥스트엔터테인먼트월드(NEW),라이드 온,Ride On,2022.0,중국,"액션,코미디,드라마",배급사,NaN,NaN,NaN,NaN
1,(주)넥스트엔터테인먼트월드(NEW),롱디,Long D,2022.0,한국,"멜로/로맨스,코미디",배급사,NaN,NaN,6.310730e+07,8833.0
2,(주)넥스트엔터테인먼트월드(NEW),두다다쿵: 후후섬의 비밀,Duda&Dada The Secret of HooHoo Island,2022.0,한국,애니메이션,배급사,1.116887e+09,123910.0,1.136159e+09,125944.0
3,(주)넥스트엔터테인먼트월드(NEW),더 퍼스트 슬램덩크,The First Slam Dunk,2022.0,일본,애니메이션,배급사,4.462225e+10,4331366.0,4.828446e+10,4629332.0
4,(주)넥스트엔터테인먼트월드(NEW),핑크퐁 시네마 콘서트 2: 원더스타 콘서트 대작전,Pinkfong Sing-Along Movie 2: Wonderstar Concert,2022.0,한국,애니메이션,배급사,4.648744e+08,50204.0,4.695594e+08,50853.0
...,...,...,...,...,...,...,...,...,...,...,...
4677,한국소니픽쳐스릴리징브에나비스타영화㈜,쿠스코? 쿠스코!,The Emperor's New Groove,2000.0,미국,애니메이션,"배급사,수입사",0.000000e+00,77754.0,NaN,NaN
4678,한국소니픽쳐스릴리징브에나비스타영화㈜,6번째 날,The 6th Day,2000.0,미국,"SF,액션,스릴러","배급사,제공",0.000000e+00,347487.0,NaN,NaN
4679,한국소니픽쳐스릴리징브에나비스타영화㈜,팀 버튼의 크리스마스 악몽,Tim Burton's The Nightmare Before Christmas,1993.0,미국,"애니메이션,가족,판타지","배급사,수입사",0.000000e+00,54928.0,4.731390e+08,53609.0
4680,한국소니픽쳐스릴리징브에나비스타영화㈜,미녀와 야수,Beauty and the Beast,1991.0,미국,"애니메이션,드라마,가족","배급사,수입사",0.000000e+00,590904.0,1.525094e+09,148966.0
4681,한국소니픽쳐스릴리징브에나비스타영화㈜,스파이더맨 3,Spider-Man 3,NaN,미국,"액션,SF","배급사,수입사",0.000000e+00,4935660.0,2.951166e+10,4592309.0

# 제작사 필터링

In [58]:
producer_datas = filmo_data[filmo_data['분야'].str.contains('제작사')]
producer_datas

,배급사,영화명,영화명(영문),제작연도,제작국가,장르,분야,공식통계 매출액,공식통계 관객수,KOBIS통계 매출액,KOBIS통계 관객수
141,(주)넥스트엔터테인먼트월드(NEW),사어,Mege Fin,2013.0,"한국,중국","사극,액션,어드벤처","제작사,배급사",NaN,NaN,NaN,NaN
236,(주)대명문화공장,신세계,New World,2012.0,한국,"범죄,액션",제작사,3.488133e+10,4682492.0,3.492725e+10,4689828.0
238,(주)대명문화공장,원더풀 라디오,Love On-Air,2011.0,한국,"드라마,멜로/로맨스",제작사,7.255598e+09,986287.0,7.255598e+09,986287.0
239,(주)대명문화공장,챔프,Champ,2011.0,한국,드라마,"제작사,공동제공",3.850214e+09,534752.0,3.850241e+09,535657.0
244,(주)덱스터스튜디오,모가디슈,Escape from Mogadishu,2021.0,한국,"액션,드라마",제작사,3.455830e+10,3613984.0,3.460172e+10,3619202.0
...,...,...,...,...,...,...,...,...,...,...,...
4354,판씨네마㈜,예언자,A Prophet,2009.0,프랑스,"드라마,범죄","제작사,배급사,수입사",1.960856e+08,25309.0,1.944378e+08,25097.0
4356,판씨네마㈜,호우시절,A Good Rain Knows,2009.0,"한국,중국",멜로/로맨스,"제작사,해외세일즈사",2.165020e+09,291143.0,2.146712e+09,288631.0
4388,플러스엠 엔터테인먼트,화란,Hopeless,2022.0,한국,드라마,"제작사,배급사,제공",NaN,NaN,NaN,NaN
4390,플러스엠 엔터테인먼트,서울괴담,Urban Myths,2021.0,한국,공포(호러),"제작사,배급사,제공",1.076281e+09,112725.0,1.076281e+09,112725.0
4453,플러스엠 엔터테인먼트,미쓰 와이프,Wonderful Nightmare,2015.0,한국,코미디,"제작사,배급사,해외세일즈사",7.387087e+09,988451.0,7.387087e+09,988451.0

# 사용 컬럼 선택

In [59]:
producer_data = producer_datas[['배급사', '영화명', '공식통계 매출액','KOBIS통계 매출액']]
producer_data

                      배급사      영화명      공식통계 매출액   KOBIS통계 매출액
141   (주)넥스트엔터테인먼트월드(NEW)       사어           NaN           NaN
236             (주)대명문화공장      신세계  3.488133e+10  3.492725e+10
238             (주)대명문화공장  원더풀 라디오  7.255598e+09  7.255598e+09
239             (주)대명문화공장       챔프  3.850214e+09  3.850241e+09
244            (주)덱스터스튜디오     모가디슈  3.455830e+10  3.460172e+10
...                   ...      ...           ...           ...
4354                판씨네마㈜      예언자  1.960856e+08  1.944378e+08
4356                판씨네마㈜     호우시절  2.165020e+09  2.146712e+09
4388          플러스엠 엔터테인먼트       화란           NaN           NaN
4390          플러스엠 엔터테인먼트     서울괴담  1.076281e+09  1.076281e+09
4453          플러스엠 엔터테인먼트   미쓰 와이프  7.387087e+09  7.387087e+09

[261 rows x 4 columns]

# 결측값 확인

In [60]:
producer_data[['배급사', '공식통계 매출액']].isnull().sum()

배급사          0
공식통계 매출액    28
dtype: int64

In [74]:
producer_data.iloc[[0],[2]]

     공식통계 매출액
141       NaN

In [65]:
producer_data.iloc[[0]]

                     배급사 영화명  공식통계 매출액  KOBIS통계 매출액
141  (주)넥스트엔터테인먼트월드(NEW)  사어       NaN          NaN

# 결측값 대체

In [77]:
for i in range(len(producer_data)):
    if producer_data.iloc[i,2] > 0:
        producer_data.iloc[[i],[2]] = producer_data.iloc[[i],[3]]
producer_data

                      배급사      영화명      공식통계 매출액   KOBIS통계 매출액
141   (주)넥스트엔터테인먼트월드(NEW)       사어           NaN           NaN
236             (주)대명문화공장      신세계  3.492725e+10  3.492725e+10
238             (주)대명문화공장  원더풀 라디오  7.255598e+09  7.255598e+09
239             (주)대명문화공장       챔프  3.850241e+09  3.850241e+09
244            (주)덱스터스튜디오     모가디슈  3.460172e+10  3.460172e+10
...                   ...      ...           ...           ...
4354                판씨네마㈜      예언자  1.944378e+08  1.944378e+08
4356                판씨네마㈜     호우시절  2.146712e+09  2.146712e+09
4388          플러스엠 엔터테인먼트       화란           NaN           NaN
4390          플러스엠 엔터테인먼트     서울괴담  1.076281e+09  1.076281e+09
4453          플러스엠 엔터테인먼트   미쓰 와이프  7.387087e+09  7.387087e+09

[261 rows x 4 columns]

# 결측값 확인, 제거

In [78]:
# KOBIS통계 매출액 공식 통계 매출액으로 대체
producer_data[producer_data['공식통계 매출액'].isnull()]

                      배급사         영화명  공식통계 매출액  KOBIS통계 매출액
141   (주)넥스트엔터테인먼트월드(NEW)          사어       NaN          NaN
418                (주)쇼박스     어나더 레코드       NaN          NaN
682               (주)싸이더스     한국이 싫어서       NaN          NaN
871               (주)싸이더스  결혼은, 미친짓이다       NaN          NaN
872               (주)싸이더스        정글쥬스       NaN          NaN
...                   ...         ...       ...          ...
4158           이십세기폭스코리아㈜    잠망경을 올려라       NaN          NaN
4159           이십세기폭스코리아㈜    사랑을 기다리며       NaN          NaN
4164           이십세기폭스코리아㈜        이중노출       NaN          NaN
4211           이십세기폭스코리아㈜     7인의 독수리       NaN          NaN
4388          플러스엠 엔터테인먼트          화란       NaN          NaN

[68 rows x 4 columns]

In [82]:
producer_data = producer_data.dropna(axis = 0)
producer_data

              배급사           영화명      공식통계 매출액   KOBIS통계 매출액
236     (주)대명문화공장           신세계  3.492725e+10  3.492725e+10
238     (주)대명문화공장       원더풀 라디오  7.255598e+09  7.255598e+09
239     (주)대명문화공장            챔프  3.850241e+09  3.850241e+09
244    (주)덱스터스튜디오          모가디슈  3.460172e+10  3.460172e+10
246    (주)덱스터스튜디오  힘을 내요, 미스터 리  9.930519e+09  9.930519e+09
...           ...           ...           ...           ...
4335        판씨네마㈜          봄, 눈  1.435180e+08  1.435180e+08
4354        판씨네마㈜           예언자  1.944378e+08  1.944378e+08
4356        판씨네마㈜          호우시절  2.146712e+09  2.146712e+09
4390  플러스엠 엔터테인먼트          서울괴담  1.076281e+09  1.076281e+09
4453  플러스엠 엔터테인먼트        미쓰 와이프  7.387087e+09  7.387087e+09

[193 rows x 4 columns]

In [91]:
# 매출액이 0인 행 삭제
producer_data[producer_data['공식통계 매출액'] == 0]

              배급사  영화명  공식통계 매출액  KOBIS통계 매출액
3358  워너브러더스 코리아㈜  크로우       0.0          0.0

In [92]:
# 현재 데이터프레임 확인
producer_data = producer_data.drop(producer_data[producer_data['공식통계 매출액'] == 0].index)
producer_data

              배급사           영화명      공식통계 매출액   KOBIS통계 매출액
236     (주)대명문화공장           신세계  3.492725e+10  3.492725e+10
238     (주)대명문화공장       원더풀 라디오  7.255598e+09  7.255598e+09
239     (주)대명문화공장            챔프  3.850241e+09  3.850241e+09
244    (주)덱스터스튜디오          모가디슈  3.460172e+10  3.460172e+10
246    (주)덱스터스튜디오  힘을 내요, 미스터 리  9.930519e+09  9.930519e+09
...           ...           ...           ...           ...
4335        판씨네마㈜          봄, 눈  1.435180e+08  1.435180e+08
4354        판씨네마㈜           예언자  1.944378e+08  1.944378e+08
4356        판씨네마㈜          호우시절  2.146712e+09  2.146712e+09
4390  플러스엠 엔터테인먼트          서울괴담  1.076281e+09  1.076281e+09
4453  플러스엠 엔터테인먼트        미쓰 와이프  7.387087e+09  7.387087e+09

[192 rows x 4 columns]

# 필요 없는 컬럼 삭제

In [96]:
# KOBIS 통계 매출액 컬럼 삭제
producer_data = producer_data.drop(columns='KOBIS통계 매출액')
producer_data

              배급사           영화명      공식통계 매출액
236     (주)대명문화공장           신세계  3.492725e+10
238     (주)대명문화공장       원더풀 라디오  7.255598e+09
239     (주)대명문화공장            챔프  3.850241e+09
244    (주)덱스터스튜디오          모가디슈  3.460172e+10
246    (주)덱스터스튜디오  힘을 내요, 미스터 리  9.930519e+09
...           ...           ...           ...
4335        판씨네마㈜          봄, 눈  1.435180e+08
4354        판씨네마㈜           예언자  1.944378e+08
4356        판씨네마㈜          호우시절  2.146712e+09
4390  플러스엠 엔터테인먼트          서울괴담  1.076281e+09
4453  플러스엠 엔터테인먼트        미쓰 와이프  7.387087e+09

[192 rows x 3 columns]

In [98]:
producer_data[producer_data['배급사'] == '(주)대명문화공장']

           배급사      영화명      공식통계 매출액
236  (주)대명문화공장      신세계  3.492725e+10
238  (주)대명문화공장  원더풀 라디오  7.255598e+09
239  (주)대명문화공장       챔프  3.850241e+09

# 제작사별 단편 최고 매출액, 영화명 추출
## (기본 프레임)

In [153]:
bb = producer_data.loc[producer_data.groupby(['배급사'])['공식통계 매출액'].idxmax()]
bb

                      배급사                   영화명      공식통계 매출액
236             (주)대명문화공장                   신세계  3.492725e+10
248            (주)덱스터스튜디오             신과함께-죄와 벌  1.157275e+11
477                (주)쇼박스                    관상  6.600983e+10
676          (주)시네마서비스글로벌        강철중: 공공의 적 1-1  2.863847e+10
841               (주)싸이더스                    타짜  3.626348e+10
968             (주)씨제이이엔엠                  극한직업  1.396555e+11
1960        롯데쇼핑㈜롯데엔터테인먼트                아이들...  1.357971e+10
2359    롯데컬처웍스(주)롯데엔터테인먼트                아이들...  1.357971e+10
2531       브에나비스타인터내셔널코리아         에브리원 세즈 아이러브유  4.980000e+05
3121          워너브러더스 코리아㈜                    밀정  6.127008e+10
3544         월트디즈니컴퍼니코리아㈜           프린세스 다이어리 2  7.920405e+08
3684  유니버설픽쳐스인터내셔널 코리아(유)                    로우  2.298450e+07
4136           이십세기폭스코리아㈜  스타워즈:에피소드1 보이지 않는 위험  1.230735e+09
4356                판씨네마㈜                  호우시절  2.146712e+09
4453          플러스엠 엔터테인먼트                미쓰 와이프  7.387087e+09

# 제작사별 제작 작품수 추출, 병합

In [154]:
# 제작사별 제작 작품수
tot_cnt = pd.DataFrame(producer_data.groupby("배급사")['공식통계 매출액'].count())
tot_cnt = tot_cnt.rename(columns={'공식통계 매출액': '제작 작품수'})
tot_cnt = tot_cnt.reset_index()
tot_cnt

                    배급사  제작 작품수
0             (주)대명문화공장       3
1            (주)덱스터스튜디오       4
2                (주)쇼박스      22
3          (주)시네마서비스글로벌       8
4               (주)싸이더스      60
5             (주)씨제이이엔엠      62
6         롯데쇼핑㈜롯데엔터테인먼트       4
7     롯데컬처웍스(주)롯데엔터테인먼트       4
8        브에나비스타인터내셔널코리아       1
9           워너브러더스 코리아㈜       9
10         월트디즈니컴퍼니코리아㈜       2
11  유니버설픽쳐스인터내셔널 코리아(유)       1
12           이십세기폭스코리아㈜       7
13                판씨네마㈜       3
14          플러스엠 엔터테인먼트       2

In [155]:
bb = bb.merge(tot_cnt, on='배급사', how='left')
bb

                    배급사                   영화명      공식통계 매출액  제작 작품수
0             (주)대명문화공장                   신세계  3.492725e+10       3
1            (주)덱스터스튜디오             신과함께-죄와 벌  1.157275e+11       4
2                (주)쇼박스                    관상  6.600983e+10      22
3          (주)시네마서비스글로벌        강철중: 공공의 적 1-1  2.863847e+10       8
4               (주)싸이더스                    타짜  3.626348e+10      60
5             (주)씨제이이엔엠                  극한직업  1.396555e+11      62
6         롯데쇼핑㈜롯데엔터테인먼트                아이들...  1.357971e+10       4
7     롯데컬처웍스(주)롯데엔터테인먼트                아이들...  1.357971e+10       4
8        브에나비스타인터내셔널코리아         에브리원 세즈 아이러브유  4.980000e+05       1
9           워너브러더스 코리아㈜                    밀정  6.127008e+10       9
10         월트디즈니컴퍼니코리아㈜           프린세스 다이어리 2  7.920405e+08       2
11  유니버설픽쳐스인터내셔널 코리아(유)                    로우  2.298450e+07       1
12           이십세기폭스코리아㈜  스타워즈:에피소드1 보이지 않는 위험  1.230735e+09       7
13                판씨네마㈜                  호우시절  2.146712e+09       3
14          플러스엠 엔터테인먼트                미쓰 와이프  7.387087e+09       2

# 제작사별 총 매출 추출, 병합

In [158]:
# 제작사별 총 매출
tot_sum = pd.DataFrame(producer_data.groupby("배급사")['공식통계 매출액'].sum())
tot_sum = tot_sum.rename(columns={'공식통계 매출액': '총 매출액'})
tot_sum = tot_sum.reset_index()
tot_sum

                    배급사         총 매출액
0             (주)대명문화공장  4.603309e+10
1            (주)덱스터스튜디오  2.629491e+11
2                (주)쇼박스  4.439912e+11
3          (주)시네마서비스글로벌  1.161810e+11
4               (주)싸이더스  3.248465e+11
5             (주)씨제이이엔엠  1.119548e+12
6         롯데쇼핑㈜롯데엔터테인먼트  1.660274e+10
7     롯데컬처웍스(주)롯데엔터테인먼트  1.660274e+10
8        브에나비스타인터내셔널코리아  4.980000e+05
9           워너브러더스 코리아㈜  6.132224e+10
10         월트디즈니컴퍼니코리아㈜  8.571615e+08
11  유니버설픽쳐스인터내셔널 코리아(유)  2.298450e+07
12           이십세기폭스코리아㈜  1.820834e+09
13                판씨네마㈜  2.484667e+09
14          플러스엠 엔터테인먼트  8.463368e+09

In [159]:
bb = bb.merge(tot_sum, on='배급사', how='left')
bb

,배급사,영화명,공식통계 매출액,제작 작품수,총 매출액
0,(주)대명문화공장,신세계,3.492725e+10,3,4.603309e+10
1,(주)덱스터스튜디오,신과함께-죄와 벌,1.157275e+11,4,2.629491e+11
2,(주)쇼박스,관상,6.600983e+10,22,4.439912e+11
3,(주)시네마서비스글로벌,강철중: 공공의 적 1-1,2.863847e+10,8,1.161810e+11
4,(주)싸이더스,타짜,3.626348e+10,60,3.248465e+11
5,(주)씨제이이엔엠,극한직업,1.396555e+11,62,1.119548e+12
6,롯데쇼핑㈜롯데엔터테인먼트,아이들...,1.357971e+10,4,1.660274e+10
7,롯데컬처웍스(주)롯데엔터테인먼트,아이들...,1.357971e+10,4,1.660274e+10
8,브에나비스타인터내셔널코리아,에브리원 세즈 아이러브유,4.980000e+05,1,4.980000e+05
9,워너브러더스 코리아㈜,밀정,6.127008e+10,9,6.132224e+10
10,월트디즈니컴퍼니코리아㈜,프린세스 다이어리 2,7.920405e+08,2,8.571615e+08
11,유니버설픽쳐스인터내셔널 코리아(유),로우,2.298450e+07,1,2.298450e+07
12,이십세기폭스코리아㈜,스타워즈:에피소드1 보이지 않는 위험,1.230735e+09,7,1.820834e+09
13,판씨네마㈜,호우시절,2.146712e+09,3,2.484667e+09
14,플러스엠 엔터테인먼트,미쓰 와이프,7.387087e+09,2,8.463368e+09

# 제작사별 매출 평균 추출, 병합

In [160]:
# 제작사별 매출 평균
tot_avg = pd.DataFrame(producer_data.groupby("배급사")['공식통계 매출액'].mean())
tot_avg = tot_avg.rename(columns={'공식통계 매출액': '매출액 평균'})
tot_avg = tot_avg.reset_index()
tot_avg

                    배급사        매출액 평균
0             (주)대명문화공장  1.534436e+10
1            (주)덱스터스튜디오  6.573728e+10
2                (주)쇼박스  2.018142e+10
3          (주)시네마서비스글로벌  1.452262e+10
4               (주)싸이더스  5.414109e+09
5             (주)씨제이이엔엠  1.805722e+10
6         롯데쇼핑㈜롯데엔터테인먼트  4.150685e+09
7     롯데컬처웍스(주)롯데엔터테인먼트  4.150685e+09
8        브에나비스타인터내셔널코리아  4.980000e+05
9           워너브러더스 코리아㈜  6.813582e+09
10         월트디즈니컴퍼니코리아㈜  4.285808e+08
11  유니버설픽쳐스인터내셔널 코리아(유)  2.298450e+07
12           이십세기폭스코리아㈜  2.601191e+08
13                판씨네마㈜  8.282224e+08
14          플러스엠 엔터테인먼트  4.231684e+09

In [161]:
bb = bb.merge(tot_avg, on='배급사', how='left')
bb

,배급사,영화명,공식통계 매출액,제작 작품수,총 매출액,매출액 평균
0,(주)대명문화공장,신세계,3.492725e+10,3,4.603309e+10,1.534436e+10
1,(주)덱스터스튜디오,신과함께-죄와 벌,1.157275e+11,4,2.629491e+11,6.573728e+10
2,(주)쇼박스,관상,6.600983e+10,22,4.439912e+11,2.018142e+10
3,(주)시네마서비스글로벌,강철중: 공공의 적 1-1,2.863847e+10,8,1.161810e+11,1.452262e+10
4,(주)싸이더스,타짜,3.626348e+10,60,3.248465e+11,5.414109e+09
5,(주)씨제이이엔엠,극한직업,1.396555e+11,62,1.119548e+12,1.805722e+10
6,롯데쇼핑㈜롯데엔터테인먼트,아이들...,1.357971e+10,4,1.660274e+10,4.150685e+09
7,롯데컬처웍스(주)롯데엔터테인먼트,아이들...,1.357971e+10,4,1.660274e+10,4.150685e+09
8,브에나비스타인터내셔널코리아,에브리원 세즈 아이러브유,4.980000e+05,1,4.980000e+05,4.980000e+05
9,워너브러더스 코리아㈜,밀정,6.127008e+10,9,6.132224e+10,6.813582e+09
10,월트디즈니컴퍼니코리아㈜,프린세스 다이어리 2,7.920405e+08,2,8.571615e+08,4.285808e+08
11,유니버설픽쳐스인터내셔널 코리아(유),로우,2.298450e+07,1,2.298450e+07,2.298450e+07
12,이십세기폭스코리아㈜,스타워즈:에피소드1 보이지 않는 위험,1.230735e+09,7,1.820834e+09,2.601191e+08
13,판씨네마㈜,호우시절,2.146712e+09,3,2.484667e+09,8.282224e+08
14,플러스엠 엔터테인먼트,미쓰 와이프,7.387087e+09,2,8.463368e+09,4.231684e+09

# 컬럼 순서 변경

In [162]:
bb = bb[['배급사', '제작 작품수', '영화명', '공식통계 매출액', '총 매출액', '매출액 평균']]
bb

,배급사,제작 작품수,영화명,공식통계 매출액,총 매출액,매출액 평균
0,(주)대명문화공장,3,신세계,3.492725e+10,4.603309e+10,1.534436e+10
1,(주)덱스터스튜디오,4,신과함께-죄와 벌,1.157275e+11,2.629491e+11,6.573728e+10
2,(주)쇼박스,22,관상,6.600983e+10,4.439912e+11,2.018142e+10
3,(주)시네마서비스글로벌,8,강철중: 공공의 적 1-1,2.863847e+10,1.161810e+11,1.452262e+10
4,(주)싸이더스,60,타짜,3.626348e+10,3.248465e+11,5.414109e+09
5,(주)씨제이이엔엠,62,극한직업,1.396555e+11,1.119548e+12,1.805722e+10
6,롯데쇼핑㈜롯데엔터테인먼트,4,아이들...,1.357971e+10,1.660274e+10,4.150685e+09
7,롯데컬처웍스(주)롯데엔터테인먼트,4,아이들...,1.357971e+10,1.660274e+10,4.150685e+09
8,브에나비스타인터내셔널코리아,1,에브리원 세즈 아이러브유,4.980000e+05,4.980000e+05,4.980000e+05
9,워너브러더스 코리아㈜,9,밀정,6.127008e+10,6.132224e+10,6.813582e+09
10,월트디즈니컴퍼니코리아㈜,2,프린세스 다이어리 2,7.920405e+08,8.571615e+08,4.285808e+08
11,유니버설픽쳐스인터내셔널 코리아(유),1,로우,2.298450e+07,2.298450e+07,2.298450e+07
12,이십세기폭스코리아㈜,7,스타워즈:에피소드1 보이지 않는 위험,1.230735e+09,1.820834e+09,2.601191e+08
13,판씨네마㈜,3,호우시절,2.146712e+09,2.484667e+09,8.282224e+08
14,플러스엠 엔터테인먼트,2,미쓰 와이프,7.387087e+09,8.463368e+09,4.231684e+09

# 컬럼명 변경

In [165]:
bb = bb.rename(columns={'배급사':'제작사', '공식통계 매출액':'단편 최고 매출액'})
bb

,제작사,제작 작품수,영화명,단편 최고 매출액,총 매출액,매출액 평균
0,(주)대명문화공장,3,신세계,3.492725e+10,4.603309e+10,1.534436e+10
1,(주)덱스터스튜디오,4,신과함께-죄와 벌,1.157275e+11,2.629491e+11,6.573728e+10
2,(주)쇼박스,22,관상,6.600983e+10,4.439912e+11,2.018142e+10
3,(주)시네마서비스글로벌,8,강철중: 공공의 적 1-1,2.863847e+10,1.161810e+11,1.452262e+10
4,(주)싸이더스,60,타짜,3.626348e+10,3.248465e+11,5.414109e+09
5,(주)씨제이이엔엠,62,극한직업,1.396555e+11,1.119548e+12,1.805722e+10
6,롯데쇼핑㈜롯데엔터테인먼트,4,아이들...,1.357971e+10,1.660274e+10,4.150685e+09
7,롯데컬처웍스(주)롯데엔터테인먼트,4,아이들...,1.357971e+10,1.660274e+10,4.150685e+09
8,브에나비스타인터내셔널코리아,1,에브리원 세즈 아이러브유,4.980000e+05,4.980000e+05,4.980000e+05
9,워너브러더스 코리아㈜,9,밀정,6.127008e+10,6.132224e+10,6.813582e+09
10,월트디즈니컴퍼니코리아㈜,2,프린세스 다이어리 2,7.920405e+08,8.571615e+08,4.285808e+08
11,유니버설픽쳐스인터내셔널 코리아(유),1,로우,2.298450e+07,2.298450e+07,2.298450e+07
12,이십세기폭스코리아㈜,7,스타워즈:에피소드1 보이지 않는 위험,1.230735e+09,1.820834e+09,2.601191e+08
13,판씨네마㈜,3,호우시절,2.146712e+09,2.484667e+09,8.282224e+08
14,플러스엠 엔터테인먼트,2,미쓰 와이프,7.387087e+09,8.463368e+09,4.231684e+09

# 제작사별 총 매출 대비 단편 최고 매출 비율 컬럼 추가

In [188]:
bb['총 매출 대비 단편 최고 매출 비율'] = ''
bb

,제작사,제작 작품수,영화명,단편 최고 매출액,총 매출액,매출액 평균,총 매출 대비 단편 최고 매출 비율
0,(주)대명문화공장,3,신세계,3.492725e+10,4.603309e+10,1.534436e+10,
1,(주)덱스터스튜디오,4,신과함께-죄와 벌,1.157275e+11,2.629491e+11,6.573728e+10,
2,(주)쇼박스,22,관상,6.600983e+10,4.439912e+11,2.018142e+10,
3,(주)시네마서비스글로벌,8,강철중: 공공의 적 1-1,2.863847e+10,1.161810e+11,1.452262e+10,
4,(주)싸이더스,60,타짜,3.626348e+10,3.248465e+11,5.414109e+09,
5,(주)씨제이이엔엠,62,극한직업,1.396555e+11,1.119548e+12,1.805722e+10,
6,롯데쇼핑㈜롯데엔터테인먼트,4,아이들...,1.357971e+10,1.660274e+10,4.150685e+09,
7,롯데컬처웍스(주)롯데엔터테인먼트,4,아이들...,1.357971e+10,1.660274e+10,4.150685e+09,
8,브에나비스타인터내셔널코리아,1,에브리원 세즈 아이러브유,4.980000e+05,4.980000e+05,4.980000e+05,
9,워너브러더스 코리아㈜,9,밀정,6.127008e+10,6.132224e+10,6.813582e+09,
10,월트디즈니컴퍼니코리아㈜,2,프린세스 다이어리 2,7.920405e+08,8.571615e+08,4.285808e+08,
11,유니버설픽쳐스인터내셔널 코리아(유),1,로우,2.298450e+07,2.298450e+07,2.298450e+07,
12,이십세기폭스코리아㈜,7,스타워즈:에피소드1 보이지 않는 위험,1.230735e+09,1.820834e+09,2.601191e+08,
13,판씨네마㈜,3,호우시절,2.146712e+09,2.484667e+09,8.282224e+08,
14,플러스엠 엔터테인먼트,2,미쓰 와이프,7.387087e+09,8.463368e+09,4.231684e+09,

In [191]:
# 비율 계산
bb['총 매출 대비 단편 최고 매출 비율'] = (bb['단편 최고 매출액'] / bb['총 매출액'] * 100).round(2)
bb

,제작사,제작 작품수,영화명,단편 최고 매출액,총 매출액,매출액 평균,총 매출 대비 단편 최고 매출 비율
0,(주)대명문화공장,3,신세계,3.492725e+10,4.603309e+10,1.534436e+10,75.87
1,(주)덱스터스튜디오,4,신과함께-죄와 벌,1.157275e+11,2.629491e+11,6.573728e+10,44.01
2,(주)쇼박스,22,관상,6.600983e+10,4.439912e+11,2.018142e+10,14.87
3,(주)시네마서비스글로벌,8,강철중: 공공의 적 1-1,2.863847e+10,1.161810e+11,1.452262e+10,24.65
4,(주)싸이더스,60,타짜,3.626348e+10,3.248465e+11,5.414109e+09,11.16
5,(주)씨제이이엔엠,62,극한직업,1.396555e+11,1.119548e+12,1.805722e+10,12.47
6,롯데쇼핑㈜롯데엔터테인먼트,4,아이들...,1.357971e+10,1.660274e+10,4.150685e+09,81.79
7,롯데컬처웍스(주)롯데엔터테인먼트,4,아이들...,1.357971e+10,1.660274e+10,4.150685e+09,81.79
8,브에나비스타인터내셔널코리아,1,에브리원 세즈 아이러브유,4.980000e+05,4.980000e+05,4.980000e+05,100.00
9,워너브러더스 코리아㈜,9,밀정,6.127008e+10,6.132224e+10,6.813582e+09,99.91
10,월트디즈니컴퍼니코리아㈜,2,프린세스 다이어리 2,7.920405e+08,8.571615e+08,4.285808e+08,92.40
11,유니버설픽쳐스인터내셔널 코리아(유),1,로우,2.298450e+07,2.298450e+07,2.298450e+07,100.00
12,이십세기폭스코리아㈜,7,스타워즈:에피소드1 보이지 않는 위험,1.230735e+09,1.820834e+09,2.601191e+08,67.59
13,판씨네마㈜,3,호우시절,2.146712e+09,2.484667e+09,8.282224e+08,86.40
14,플러스엠 엔터테인먼트,2,미쓰 와이프,7.387087e+09,8.463368e+09,4.231684e+09,87.28

In [194]:
bb.to_csv('./제작사.csv', index=False)