In [2]:
import pandas as pd

In [109]:
movie_200_info_data = pd.read_excel('./use_data/(완)역대_박스오피스(2023.05.11).xlsx', engine='openpyxl')
movie_200_info_data

,순위,영화명,개봉일,매출액,관객수,스크린수,상영횟수,대표국적,국적,배급사
0,1,명량,2014-07-30,135758658810,17615919,1587,188726,한국,한국,(주)씨제이이엔엠
1,2,극한직업,2019-01-23,139655543516,16266338,2003,292816,한국,한국,(주)씨제이이엔엠
2,3,신과함께-죄와 벌,2017-12-20,115727528087,14414658,1912,214631,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
3,4,국제시장,2014-12-17,110947621230,14264478,1044,212705,한국,한국,(주)씨제이이엔엠
4,5,어벤져스: 엔드게임,2019-04-24,122492181020,13977602,2835,246433,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
...,...,...,...,...,...,...,...,...,...,...
195,196,해리 포터와 불의 잔,2005-12-01,22097731900,3499257,504,45555,미국,미국,워너브러더스 코리아(주)
196,197,비긴 어게인,2014-08-13,27433947031,3479444,525,87565,미국,미국,판씨네마(주)
197,198,태풍,2005-12-14,22209675300,3471150,481,47155,한국,한국,CJ ENM
198,199,킹콩,2005-12-14,21476688172,3470059,319,38456,미국,미국,UIP코리아
199,200,부러진 화살,2012-01-18,25938096000,3460212,530,71607,한국,한국,(주)넥스트엔터테인먼트월드(NEW)

In [8]:
# movie_day_data = pd.read_excel('./use_data/기간별_일별(2017.01~2023.05)_수정.xlsx', engine='openpyxl')
# movie_day_data

,순위,영화명,개봉일,대표국적,국적,제작사,배급사,등급,장르,감독,배우,기준일,매출액,누적매출액,관객수,누적관객수,스크린수,상영횟수
0,1,너의 이름은.,2017-01-04,일본,일본,NaN,플러스엠 엔터테인먼트,12세이상관람가,"애니메이션,드라마,멜로/로맨스",신카이 마코토,"카미키 류노스케,카미시라이시 모네,나가사와 마사미,이치하라 에수코,유키 아오이,시마...",2017-01-08,2809088900,9745292442,333008,1182465,947,4101
1,2,마스터,2016-12-21,한국,한국,영화사 집,(주)씨제이이엔엠,15세이상관람가,"액션,범죄",조의석,"이병헌,강동원,김우빈,엄지원,박해수,오달수,진경,김정우,장한별,이승용,김대현,홍성덕...",2017-01-08,1903655600,52966342965,220974,6518100,866,3186
2,3,모아나,2017-01-12,미국,미국,NaN,월트디즈니컴퍼니코리아 유한책임회사,전체관람가,애니메이션,"론 클레멘츠,존 머스커","드웨인 존슨,아우이 크라발호,알란 터딕,제메인 클레멘트,테무에라 모리슨",2017-01-08,7738000,9712000,910,1192,6,6
3,4,패신저스,2017-01-04,미국,미국,NaN,유니버설픽쳐스인터내셔널 코리아(유),12세이상관람가,"어드벤처,SF",모튼 틸덤,"크리스 프랫,제니퍼 로렌스,마이클 쉰,앤디 가르시아,로렌스 피쉬번",2017-01-08,1107502600,4176443418,129810,504393,608,2272
4,5,얼라이드,2017-01-11,미국,미국,NaN,롯데쇼핑㈜롯데엔터테인먼트,15세이상관람가,"스릴러,드라마,멜로/로맨스",로버트 저메키스,"브래드 피트,마리옹 꼬띠아르,리지 캐플란,매튜 구드,자레드 해리스",2017-01-08,0,32151000,0,3730,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626369,212,문영,2017-01-12,한국,한국,NaN,KT&G 상상마당 영화사업팀 컴퍼니에스에스(주),15세이상관람가,드라마,김소연,"김태리,정현,박완규,박정식",2017-01-07,0,2819699,0,350,0,0
626370,212,이올란타 & 호두까기인형,NaT,프랑스,프랑스,NaN,에스디시코리아 주식회사,전체관람가,공연,드미트리 체르니아코프,"알렉산더 침발류크,소냐 욘체바",2017-01-07,0,0,0,0,0,0
626371,212,작은 형,2016-11-30,한국,한국,"파인스토리,(주)인베스트하우스",파인스토리,15세이상관람가,드라마,심광진,"전석호,진용욱,민지아,이혁,박성근,김민지,김구민,김준희,김지혜,이지은,이창원,한결",2017-01-07,0,11721500,0,1853,0,0
626372,212,지옥화,1958-04-20,한국,한국,서울영화사,NaN,미정,"멜로/로맨스,드라마,범죄",신상옥,"김학,최은희,조해원",2017-01-07,0,5174000,0,2577,0,0
626373,212,혈맥,NaT,한국,한국,NaN,NaN,전체관람가,드라마,김수용,"김지미,황정순,최남현",2017-01-07,0,36000,0,6,0,0

In [110]:
filmo_data = pd.read_excel('./use_data/필모그래피_통합.xlsx', engine='openpyxl')
filmo_data

,배급사,영화명,영화명(영문),제작연도,제작국가,장르,분야,공식통계 매출액,공식통계 관객수,KOBIS통계 매출액,KOBIS통계 관객수
0,(주)넥스트엔터테인먼트월드(NEW),라이드 온,Ride On,2022.0,중국,"액션,코미디,드라마",배급사,NaN,NaN,NaN,NaN
1,(주)넥스트엔터테인먼트월드(NEW),롱디,Long D,2022.0,한국,"멜로/로맨스,코미디",배급사,NaN,NaN,6.310730e+07,8833.0
2,(주)넥스트엔터테인먼트월드(NEW),두다다쿵: 후후섬의 비밀,Duda&Dada The Secret of HooHoo Island,2022.0,한국,애니메이션,배급사,1.116887e+09,123910.0,1.136159e+09,125944.0
3,(주)넥스트엔터테인먼트월드(NEW),더 퍼스트 슬램덩크,The First Slam Dunk,2022.0,일본,애니메이션,배급사,4.462225e+10,4331366.0,4.828446e+10,4629332.0
4,(주)넥스트엔터테인먼트월드(NEW),핑크퐁 시네마 콘서트 2: 원더스타 콘서트 대작전,Pinkfong Sing-Along Movie 2: Wonderstar Concert,2022.0,한국,애니메이션,배급사,4.648744e+08,50204.0,4.695594e+08,50853.0
...,...,...,...,...,...,...,...,...,...,...,...
4677,한국소니픽쳐스릴리징브에나비스타영화㈜,쿠스코? 쿠스코!,The Emperor's New Groove,2000.0,미국,애니메이션,"배급사,수입사",0.000000e+00,77754.0,NaN,NaN
4678,한국소니픽쳐스릴리징브에나비스타영화㈜,6번째 날,The 6th Day,2000.0,미국,"SF,액션,스릴러","배급사,제공",0.000000e+00,347487.0,NaN,NaN
4679,한국소니픽쳐스릴리징브에나비스타영화㈜,팀 버튼의 크리스마스 악몽,Tim Burton's The Nightmare Before Christmas,1993.0,미국,"애니메이션,가족,판타지","배급사,수입사",0.000000e+00,54928.0,4.731390e+08,53609.0
4680,한국소니픽쳐스릴리징브에나비스타영화㈜,미녀와 야수,Beauty and the Beast,1991.0,미국,"애니메이션,드라마,가족","배급사,수입사",0.000000e+00,590904.0,1.525094e+09,148966.0
4681,한국소니픽쳐스릴리징브에나비스타영화㈜,스파이더맨 3,Spider-Man 3,NaN,미국,"액션,SF","배급사,수입사",0.000000e+00,4935660.0,2.951166e+10,4592309.0

In [111]:
# 배급사만 추출
filmo_data = filmo_data[filmo_data['분야'].str.contains('배급사')]
filmo_data

,배급사,영화명,영화명(영문),제작연도,제작국가,장르,분야,공식통계 매출액,공식통계 관객수,KOBIS통계 매출액,KOBIS통계 관객수
0,(주)넥스트엔터테인먼트월드(NEW),라이드 온,Ride On,2022.0,중국,"액션,코미디,드라마",배급사,NaN,NaN,NaN,NaN
1,(주)넥스트엔터테인먼트월드(NEW),롱디,Long D,2022.0,한국,"멜로/로맨스,코미디",배급사,NaN,NaN,6.310730e+07,8833.0
2,(주)넥스트엔터테인먼트월드(NEW),두다다쿵: 후후섬의 비밀,Duda&Dada The Secret of HooHoo Island,2022.0,한국,애니메이션,배급사,1.116887e+09,123910.0,1.136159e+09,125944.0
3,(주)넥스트엔터테인먼트월드(NEW),더 퍼스트 슬램덩크,The First Slam Dunk,2022.0,일본,애니메이션,배급사,4.462225e+10,4331366.0,4.828446e+10,4629332.0
4,(주)넥스트엔터테인먼트월드(NEW),핑크퐁 시네마 콘서트 2: 원더스타 콘서트 대작전,Pinkfong Sing-Along Movie 2: Wonderstar Concert,2022.0,한국,애니메이션,배급사,4.648744e+08,50204.0,4.695594e+08,50853.0
...,...,...,...,...,...,...,...,...,...,...,...
4677,한국소니픽쳐스릴리징브에나비스타영화㈜,쿠스코? 쿠스코!,The Emperor's New Groove,2000.0,미국,애니메이션,"배급사,수입사",0.000000e+00,77754.0,NaN,NaN
4678,한국소니픽쳐스릴리징브에나비스타영화㈜,6번째 날,The 6th Day,2000.0,미국,"SF,액션,스릴러","배급사,제공",0.000000e+00,347487.0,NaN,NaN
4679,한국소니픽쳐스릴리징브에나비스타영화㈜,팀 버튼의 크리스마스 악몽,Tim Burton's The Nightmare Before Christmas,1993.0,미국,"애니메이션,가족,판타지","배급사,수입사",0.000000e+00,54928.0,4.731390e+08,53609.0
4680,한국소니픽쳐스릴리징브에나비스타영화㈜,미녀와 야수,Beauty and the Beast,1991.0,미국,"애니메이션,드라마,가족","배급사,수입사",0.000000e+00,590904.0,1.525094e+09,148966.0
4681,한국소니픽쳐스릴리징브에나비스타영화㈜,스파이더맨 3,Spider-Man 3,NaN,미국,"액션,SF","배급사,수입사",0.000000e+00,4935660.0,2.951166e+10,4592309.0

# 역대 영화의 배급사 검색

In [112]:
movie_200_info_data

,순위,영화명,개봉일,매출액,관객수,스크린수,상영횟수,대표국적,국적,배급사
0,1,명량,2014-07-30,135758658810,17615919,1587,188726,한국,한국,(주)씨제이이엔엠
1,2,극한직업,2019-01-23,139655543516,16266338,2003,292816,한국,한국,(주)씨제이이엔엠
2,3,신과함께-죄와 벌,2017-12-20,115727528087,14414658,1912,214631,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
3,4,국제시장,2014-12-17,110947621230,14264478,1044,212705,한국,한국,(주)씨제이이엔엠
4,5,어벤져스: 엔드게임,2019-04-24,122492181020,13977602,2835,246433,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
...,...,...,...,...,...,...,...,...,...,...
195,196,해리 포터와 불의 잔,2005-12-01,22097731900,3499257,504,45555,미국,미국,워너브러더스 코리아(주)
196,197,비긴 어게인,2014-08-13,27433947031,3479444,525,87565,미국,미국,판씨네마(주)
197,198,태풍,2005-12-14,22209675300,3471150,481,47155,한국,한국,CJ ENM
198,199,킹콩,2005-12-14,21476688172,3470059,319,38456,미국,미국,UIP코리아
199,200,부러진 화살,2012-01-18,25938096000,3460212,530,71607,한국,한국,(주)넥스트엔터테인먼트월드(NEW)

In [133]:
a = movie_200_info_data[['영화명', '배급사', '개봉일', '매출액', '관객수']]
a

             영화명                  배급사        개봉일           매출액       관객수
0             명량            (주)씨제이이엔엠 2014-07-30  135758658810  17615919
1           극한직업            (주)씨제이이엔엠 2019-01-23  139655543516  16266338
2      신과함께-죄와 벌        롯데쇼핑㈜롯데엔터테인먼트 2017-12-20  115727528087  14414658
3           국제시장            (주)씨제이이엔엠 2014-12-17  110947621230  14264478
4     어벤져스: 엔드게임   월트디즈니컴퍼니코리아 유한책임회사 2019-04-24  122492181020  13977602
..           ...                  ...        ...           ...       ...
195  해리 포터와 불의 잔        워너브러더스 코리아(주) 2005-12-01   22097731900   3499257
196       비긴 어게인              판씨네마(주) 2014-08-13   27433947031   3479444
197           태풍               CJ ENM 2005-12-14   22209675300   3471150
198           킹콩               UIP코리아 2005-12-14   21476688172   3470059
199       부러진 화살  (주)넥스트엔터테인먼트월드(NEW) 2012-01-18   25938096000   3460212

[200 rows x 5 columns]

In [134]:
b = filmo_data[['영화명', '배급사', '제작연도', '장르']]
b

                              영화명                  배급사    제작연도            장르
0                           라이드 온  (주)넥스트엔터테인먼트월드(NEW)  2022.0    액션,코미디,드라마
1                              롱디  (주)넥스트엔터테인먼트월드(NEW)  2022.0    멜로/로맨스,코미디
2                   두다다쿵: 후후섬의 비밀  (주)넥스트엔터테인먼트월드(NEW)  2022.0         애니메이션
3                      더 퍼스트 슬램덩크  (주)넥스트엔터테인먼트월드(NEW)  2022.0         애니메이션
4     핑크퐁 시네마 콘서트 2: 원더스타 콘서트 대작전  (주)넥스트엔터테인먼트월드(NEW)  2022.0         애니메이션
...                           ...                  ...     ...           ...
4677                    쿠스코? 쿠스코!  한국소니픽쳐스릴리징브에나비스타영화㈜  2000.0         애니메이션
4678                        6번째 날  한국소니픽쳐스릴리징브에나비스타영화㈜  2000.0     SF,액션,스릴러
4679               팀 버튼의 크리스마스 악몽  한국소니픽쳐스릴리징브에나비스타영화㈜  1993.0  애니메이션,가족,판타지
4680                       미녀와 야수  한국소니픽쳐스릴리징브에나비스타영화㈜  1991.0  애니메이션,드라마,가족
4681                      스파이더맨 3  한국소니픽쳐스릴리징브에나비스타영화㈜     NaN         액션,SF

[3986 rows x 4 columns]

In [136]:
a.set_index('영화명', inplace=True)
b.set_index('영화명', inplace=True)

In [137]:
result = a.join(b, lsuffix='_a', rsuffix='_b')
result

,배급사_a,개봉일,매출액,관객수,배급사_b,제작연도,장르
영화명,,,,,,,
1987,(주)씨제이이엔엠,2017-12-27,58170216145,7232452,(주)씨제이이엔엠,2017.0,드라마
2012,한국소니픽쳐스릴리징브에나비스타영화㈜,2009-11-12,38941723000,5397597,소니픽쳐스릴리징월트디즈니스튜디오스코리아㈜,2009.0,"SF,액션,어드벤처"
2012,한국소니픽쳐스릴리징브에나비스타영화㈜,2009-11-12,38941723000,5397597,한국소니픽쳐스릴리징브에나비스타영화㈜,2009.0,"SF,액션,어드벤처"
7급 공무원,롯데쇼핑㈜롯데엔터테인먼트,2009-04-22,26380710000,4039891,롯데쇼핑㈜롯데엔터테인먼트,2008.0,"코미디,액션,드라마,범죄"
7급 공무원,롯데쇼핑㈜롯데엔터테인먼트,2009-04-22,26380710000,4039891,롯데컬처웍스(주)롯데엔터테인먼트,2008.0,"코미디,액션,드라마,범죄"
...,...,...,...,...,...,...,...
헌트,플러스엠 엔터테인먼트,2022-08-10,44601068153,4352420,유니버설픽쳐스인터내셔널 코리아(유),2020.0,"액션,공포(호러),스릴러"
헌트,플러스엠 엔터테인먼트,2022-08-10,44601068153,4352420,플러스엠 엔터테인먼트,2022.0,"액션,드라마"
혹성탈출: 반격의 서막,이십세기폭스코리아(주),2014-07-10,31514053095,4002560,이십세기폭스코리아㈜,2014.0,"액션,드라마,SF,스릴러"
화려한 휴가,CJ ENM,2007-07-25,44098824600,6855433,(주)씨제이이엔엠,2007.0,드라마
히말라야,(주)씨제이이엔엠,2015-12-16,60175363015,7759761,(주)씨제이이엔엠,2015.0,드라마

In [141]:
result = result.reset_index()
result

,영화명,배급사_a,개봉일,매출액,관객수,배급사_b,제작연도,장르
0,1987,(주)씨제이이엔엠,2017-12-27,58170216145,7232452,(주)씨제이이엔엠,2017.0,드라마
1,2012,한국소니픽쳐스릴리징브에나비스타영화㈜,2009-11-12,38941723000,5397597,소니픽쳐스릴리징월트디즈니스튜디오스코리아㈜,2009.0,"SF,액션,어드벤처"
2,2012,한국소니픽쳐스릴리징브에나비스타영화㈜,2009-11-12,38941723000,5397597,한국소니픽쳐스릴리징브에나비스타영화㈜,2009.0,"SF,액션,어드벤처"
3,7급 공무원,롯데쇼핑㈜롯데엔터테인먼트,2009-04-22,26380710000,4039891,롯데쇼핑㈜롯데엔터테인먼트,2008.0,"코미디,액션,드라마,범죄"
4,7급 공무원,롯데쇼핑㈜롯데엔터테인먼트,2009-04-22,26380710000,4039891,롯데컬처웍스(주)롯데엔터테인먼트,2008.0,"코미디,액션,드라마,범죄"
...,...,...,...,...,...,...,...,...
236,헌트,플러스엠 엔터테인먼트,2022-08-10,44601068153,4352420,유니버설픽쳐스인터내셔널 코리아(유),2020.0,"액션,공포(호러),스릴러"
237,헌트,플러스엠 엔터테인먼트,2022-08-10,44601068153,4352420,플러스엠 엔터테인먼트,2022.0,"액션,드라마"
238,혹성탈출: 반격의 서막,이십세기폭스코리아(주),2014-07-10,31514053095,4002560,이십세기폭스코리아㈜,2014.0,"액션,드라마,SF,스릴러"
239,화려한 휴가,CJ ENM,2007-07-25,44098824600,6855433,(주)씨제이이엔엠,2007.0,드라마
240,히말라야,(주)씨제이이엔엠,2015-12-16,60175363015,7759761,(주)씨제이이엔엠,2015.0,드라마

In [147]:
# 배급사_a와 배급사_b가 다른 항목 제거(역대 배급사 기준)
result = result.drop_duplicates(['영화명'])

In [148]:
result

,영화명,배급사_a,개봉일,매출액,관객수,배급사_b,제작연도,장르
0,1987,(주)씨제이이엔엠,2017-12-27,58170216145,7232452,(주)씨제이이엔엠,2017.0,드라마
1,2012,한국소니픽쳐스릴리징브에나비스타영화㈜,2009-11-12,38941723000,5397597,소니픽쳐스릴리징월트디즈니스튜디오스코리아㈜,2009.0,"SF,액션,어드벤처"
3,7급 공무원,롯데쇼핑㈜롯데엔터테인먼트,2009-04-22,26380710000,4039891,롯데쇼핑㈜롯데엔터테인먼트,2008.0,"코미디,액션,드라마,범죄"
5,7번방의 선물,(주)넥스트엔터테인먼트월드(NEW),2013-01-23,91437368170,12812144,(주)넥스트엔터테인먼트월드(NEW),2012.0,"코미디,드라마"
6,82년생 김지영,롯데컬처웍스(주)롯데엔터테인먼트,2019-10-23,30306859310,3679162,롯데컬처웍스(주)롯데엔터테인먼트,2019.0,드라마
...,...,...,...,...,...,...,...,...
234,해적: 바다로 간 산적,롯데쇼핑㈜롯데엔터테인먼트,2014-08-06,66372140706,8666208,롯데쇼핑㈜롯데엔터테인먼트,2014.0,어드벤처
236,헌트,플러스엠 엔터테인먼트,2022-08-10,44601068153,4352420,유니버설픽쳐스인터내셔널 코리아(유),2020.0,"액션,공포(호러),스릴러"
238,혹성탈출: 반격의 서막,이십세기폭스코리아(주),2014-07-10,31514053095,4002560,이십세기폭스코리아㈜,2014.0,"액션,드라마,SF,스릴러"
239,화려한 휴가,CJ ENM,2007-07-25,44098824600,6855433,(주)씨제이이엔엠,2007.0,드라마
240,히말라야,(주)씨제이이엔엠,2015-12-16,60175363015,7759761,(주)씨제이이엔엠,2015.0,드라마

In [155]:
result[result['배급사_a'] != result['배급사_b']]

,영화명,배급사_a,개봉일,매출액,관객수,배급사_b,제작연도,장르
1,2012,한국소니픽쳐스릴리징브에나비스타영화㈜,2009-11-12,38941723000,5397597,소니픽쳐스릴리징월트디즈니스튜디오스코리아㈜,2009.0,"SF,액션,어드벤처"
10,강철중: 공공의 적 1-1,"CJ ENM,(주)시네마서비스",2008-06-19,28638465100,4313102,(주)씨제이이엔엠,2008.0,"드라마,액션"
15,겨울왕국,소니픽쳐스릴리징월트디즈니스튜디오스코리아(주),2014-01-16,82544207680,10305051,소니픽쳐스릴리징월트디즈니스튜디오스코리아㈜,2013.0,"애니메이션,어드벤처,가족,코미디,뮤지컬,판타지"
17,곡성,이십세기폭스코리아(주),2016-05-12,55864308382,6879989,이십세기폭스코리아㈜,2016.0,"미스터리,스릴러,드라마"
42,"님아, 그 강을 건너지 마오","CGV아트하우스,(주)대명문화공장",2014-11-27,37360250579,4802642,(주)대명문화공장,2014.0,다큐멘터리
...,...,...,...,...,...,...,...,...
232,해리포터와 죽음의 성물2,워너브러더스 코리아(주),2011-07-13,34668545500,4421210,워너브러더스 코리아㈜,2011.0,"판타지,미스터리"
233,해운대,CJ ENM,2009-07-22,81028720000,11325117,(주)씨제이이엔엠,2009.0,"액션,드라마,어드벤처"
236,헌트,플러스엠 엔터테인먼트,2022-08-10,44601068153,4352420,유니버설픽쳐스인터내셔널 코리아(유),2020.0,"액션,공포(호러),스릴러"
238,혹성탈출: 반격의 서막,이십세기폭스코리아(주),2014-07-10,31514053095,4002560,이십세기폭스코리아㈜,2014.0,"액션,드라마,SF,스릴러"
239,화려한 휴가,CJ ENM,2007-07-25,44098824600,6855433,(주)씨제이이엔엠,2007.0,드라마

In [156]:
# 배급사_b 컬럼 제거
result.drop('배급사_b', axis=1, inplace=True)

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_9832\1452286813.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop('배급사_b', axis=1, inplace=True)

In [158]:
# 배급사_a 컬럼 배급사로 변경
result.rename(columns={'배급사_a' : '배급사'}, inplace=True)

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_9832\2176307801.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.rename(columns={'배급사_a' : '배급사'}, inplace=True)

In [159]:
result

,영화명,배급사,개봉일,매출액,관객수,제작연도,장르
0,1987,(주)씨제이이엔엠,2017-12-27,58170216145,7232452,2017.0,드라마
1,2012,한국소니픽쳐스릴리징브에나비스타영화㈜,2009-11-12,38941723000,5397597,2009.0,"SF,액션,어드벤처"
3,7급 공무원,롯데쇼핑㈜롯데엔터테인먼트,2009-04-22,26380710000,4039891,2008.0,"코미디,액션,드라마,범죄"
5,7번방의 선물,(주)넥스트엔터테인먼트월드(NEW),2013-01-23,91437368170,12812144,2012.0,"코미디,드라마"
6,82년생 김지영,롯데컬처웍스(주)롯데엔터테인먼트,2019-10-23,30306859310,3679162,2019.0,드라마
...,...,...,...,...,...,...,...
234,해적: 바다로 간 산적,롯데쇼핑㈜롯데엔터테인먼트,2014-08-06,66372140706,8666208,2014.0,어드벤처
236,헌트,플러스엠 엔터테인먼트,2022-08-10,44601068153,4352420,2020.0,"액션,공포(호러),스릴러"
238,혹성탈출: 반격의 서막,이십세기폭스코리아(주),2014-07-10,31514053095,4002560,2014.0,"액션,드라마,SF,스릴러"
239,화려한 휴가,CJ ENM,2007-07-25,44098824600,6855433,2007.0,드라마
240,히말라야,(주)씨제이이엔엠,2015-12-16,60175363015,7759761,2015.0,드라마

In [161]:
result.to_csv('./역대영화+필모그래피.csv', index=False)